# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: self-host-lab4

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)/WebApp.zip" /p:DeployIisAppPath="Default Web Site" /p:VisualStudioVersion=15.0 /p:MSBuildExtensionsPath=/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/msbuild/15.0/bin/'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
  testAssemblyVer2: |
    **/bin/$(BuildConfiguration)/**/*Test*.dll
    !**/bin/$(BuildConfiguration)/**/xunit.runner.visualstudio.testadapter.dll
    !**/bin/$(BuildConfiguration)/**/xunit.runner.console.dll
  platform: '$(buildPlatform)'
  configuration: '$(buildConfiguration)'
  searchFolder: '$(System.DefaultWorkingDirectory)'
  otherConsoleOptions: '/Framework:FrameworkCore10 /logger:trx /TestAdapterPath:.'
  vstestPath: '/Applications/Visual Studio.app/Contents/MacOS/vstest.console'

