# YAML file for Azure DevOps CI pipeline

trigger:
  branches:
    include:
    - main
    - development

pool:
  name: self-host-lab4

steps:
- script: dotnet build --configuration Release
  displayName: 'Build the .NET Core application'
- script: dotnet test --configuration Release --logger trx
  displayName: 'Run unit tests'
